---
title: "R_basic"
author: "Federico Dallo"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Let's start!

## Use the BerkeleyHub resources or install {.tabset}

### test

Here in Berkeley you have access to Jupyter and Rstudio: <https://datahub.berkeley.edu/>

But if you need to install R you can find it here: <https://cloud.r-project.org>

R do not comes with RStudio, which is the main IDE for R. You can install the RStudio Desktop from here: <https://www.rstudio.com/products/rstudio/>

### gigi

## General interaction with R environment(s)
```{r}
"Hello Cal!" # this is an explicit print
```

```{r}
5 # this is a number.. 
```

```{r}
is.numeric(5) # this is a number.. 
```

```{r}
typeof(5) # but what kind of number??
```

```{r}
# Can I force to have another representation?
typeof( as.integer(5) )
print( as.integer(5) ) # we need to explicitly invoke the "print" function
typeof( as.character(5) )
print( as.character(5) )
```

```{r}
for (i in 1:5) {print(i)}
```

## Arithmetics 
